# Usa imagem oficial do Node 24
FROM node:24

# Diretório de trabalho
WORKDIR /app

# Copia arquivos necessários para instalar as dependências node_modules EM TEMPO DE BUILD
COPY package*.json ./
COPY _worker.js ./

# Cria diretório Jobs se não existir e copia se houver arquivos
RUN mkdir -p ./app/Jobs
COPY app/Jobs/ ./app/Jobs/

# Instala dependências + nodemon para "ouvir" as mudanças
RUN npm install -g nodemon && npm install

# Comando padrão ao iniciar o container
ENTRYPOINT ["node", "_worker.js"]